name: violencia_rj
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - r-base=4.3.0
  - r-essentials
  - jupyter
  - ipykernel
  - pandas>=2.0.0
  - numpy>=1.24.0
  - geopandas>=0.13.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0
  - folium>=0.14.0
  - requests>=2.31.0
  - beautifulsoup4>=4.12.0
  - rpy2>=3.5.0
  - pip
  - pip:
    - prophet>=1.1.0
    - xgboost>=1.7.0
    - lightgbm>=4.0.0
    - tensorflow>=2.13.0
    - keras>=2.13.0
    - aiohttp>=3.8.0
    - selenium>=4.11.0
    - pyproj>=3.6.0
    - rasterio>=1.3.0
    - fiona>=1.9.0
    - tqdm>=4.65.0
    - python-dotenv>=1.0.0
    - pyyaml>=6.0.0
    - openpyxl>=3.1.0
