[tool.pylsp-mypy]
enabled = false

[tool.pylsp-rope]
enabled = false

[tool.pylsp-mccabe]
enabled = false

[tool.pylsp-flake8]
enabled = false

[tool.pylsp-pylint]
enabled = false

[tool.pylsp-pycodestyle]
enabled = false

[tool.pylsp-pyflakes]
enabled = false